/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.parser;

import bemtevi.node.*;
import bemtevi.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTPrimitivo(@SuppressWarnings("unused") TPrimitivo node)
    {
        this.index = 0;
    }

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 1;
    }

    @Override
    public void caseTVerdade(@SuppressWarnings("unused") TVerdade node)
    {
        this.index = 2;
    }

    @Override
    public void caseTFalso(@SuppressWarnings("unused") TFalso node)
    {
        this.index = 3;
    }

    @Override
    public void caseTMolde(@SuppressWarnings("unused") TMolde node)
    {
        this.index = 4;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 5;
    }

    @Override
    public void caseTEntao(@SuppressWarnings("unused") TEntao node)
    {
        this.index = 6;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 7;
    }

    @Override
    public void caseTPassa(@SuppressWarnings("unused") TPassa node)
    {
        this.index = 8;
    }

    @Override
    public void caseTPor(@SuppressWarnings("unused") TPor node)
    {
        this.index = 9;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 10;
    }

    @Override
    public void caseTContem(@SuppressWarnings("unused") TContem node)
    {
        this.index = 11;
    }

    @Override
    public void caseTConstante(@SuppressWarnings("unused") TConstante node)
    {
        this.index = 12;
    }

    @Override
    public void caseTFuncao(@SuppressWarnings("unused") TFuncao node)
    {
        this.index = 13;
    }

    @Override
    public void caseTObjeto(@SuppressWarnings("unused") TObjeto node)
    {
        this.index = 14;
    }

    @Override
    public void caseTFim(@SuppressWarnings("unused") TFim node)
    {
        this.index = 15;
    }

    @Override
    public void caseTSeparador(@SuppressWarnings("unused") TSeparador node)
    {
        this.index = 16;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 17;
    }

    @Override
    public void caseTPontoFinal(@SuppressWarnings("unused") TPontoFinal node)
    {
        this.index = 18;
    }

    @Override
    public void caseTAbreParenteses(@SuppressWarnings("unused") TAbreParenteses node)
    {
        this.index = 19;
    }

    @Override
    public void caseTFechaParenteses(@SuppressWarnings("unused") TFechaParenteses node)
    {
        this.index = 20;
    }

    @Override
    public void caseTAbreColchete(@SuppressWarnings("unused") TAbreColchete node)
    {
        this.index = 21;
    }

    @Override
    public void caseTFechaColchete(@SuppressWarnings("unused") TFechaColchete node)
    {
        this.index = 22;
    }

    @Override
    public void caseTAbreAspas(@SuppressWarnings("unused") TAbreAspas node)
    {
        this.index = 23;
    }

    @Override
    public void caseTMultiplicacao(@SuppressWarnings("unused") TMultiplicacao node)
    {
        this.index = 24;
    }

    @Override
    public void caseTSoma(@SuppressWarnings("unused") TSoma node)
    {
        this.index = 25;
    }

    @Override
    public void caseTSubtracao(@SuppressWarnings("unused") TSubtracao node)
    {
        this.index = 26;
    }

    @Override
    public void caseTDivisao(@SuppressWarnings("unused") TDivisao node)
    {
        this.index = 27;
    }

    @Override
    public void caseTModulo(@SuppressWarnings("unused") TModulo node)
    {
        this.index = 28;
    }

    @Override
    public void caseTIgualIgual(@SuppressWarnings("unused") TIgualIgual node)
    {
        this.index = 29;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 30;
    }

    @Override
    public void caseTMenorQue(@SuppressWarnings("unused") TMenorQue node)
    {
        this.index = 31;
    }

    @Override
    public void caseTMenorIgual(@SuppressWarnings("unused") TMenorIgual node)
    {
        this.index = 32;
    }

    @Override
    public void caseTExclamacao(@SuppressWarnings("unused") TExclamacao node)
    {
        this.index = 33;
    }

    @Override
    public void caseTE(@SuppressWarnings("unused") TE node)
    {
        this.index = 34;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 35;
    }

    @Override
    public void caseTEntrada(@SuppressWarnings("unused") TEntrada node)
    {
        this.index = 36;
    }

    @Override
    public void caseTIdMolde(@SuppressWarnings("unused") TIdMolde node)
    {
        this.index = 37;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 38;
    }

    @Override
    public void caseTTexto(@SuppressWarnings("unused") TTexto node)
    {
        this.index = 39;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 40;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 41;
    }
}
