/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import java.util.*;
import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoExp extends PExp
{
    private final LinkedList<PBlocoFecho> _blocoFecho_ = new LinkedList<PBlocoFecho>();
    private PExp _exp_;

    public ABlocoExp()
    {
        // Constructor
    }

    public ABlocoExp(
        @SuppressWarnings("hiding") List<?> _blocoFecho_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setBlocoFecho(_blocoFecho_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoExp(
            cloneList(this._blocoFecho_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoExp(this);
    }

    public LinkedList<PBlocoFecho> getBlocoFecho()
    {
        return this._blocoFecho_;
    }

    public void setBlocoFecho(List<?> list)
    {
        for(PBlocoFecho e : this._blocoFecho_)
        {
            e.parent(null);
        }
        this._blocoFecho_.clear();

        for(Object obj_e : list)
        {
            PBlocoFecho e = (PBlocoFecho) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._blocoFecho_.add(e);
        }
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blocoFecho_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blocoFecho_.remove(child))
        {
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PBlocoFecho> i = this._blocoFecho_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PBlocoFecho) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
