/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ADefMolde extends PDefMolde
{
    private TIdMolde _idMolde_;
    private PAtributos _atributos_;
    private PMetodos _metodos_;

    public ADefMolde()
    {
        // Constructor
    }

    public ADefMolde(
        @SuppressWarnings("hiding") TIdMolde _idMolde_,
        @SuppressWarnings("hiding") PAtributos _atributos_,
        @SuppressWarnings("hiding") PMetodos _metodos_)
    {
        // Constructor
        setIdMolde(_idMolde_);

        setAtributos(_atributos_);

        setMetodos(_metodos_);

    }

    @Override
    public Object clone()
    {
        return new ADefMolde(
            cloneNode(this._idMolde_),
            cloneNode(this._atributos_),
            cloneNode(this._metodos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefMolde(this);
    }

    public TIdMolde getIdMolde()
    {
        return this._idMolde_;
    }

    public void setIdMolde(TIdMolde node)
    {
        if(this._idMolde_ != null)
        {
            this._idMolde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idMolde_ = node;
    }

    public PAtributos getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(PAtributos node)
    {
        if(this._atributos_ != null)
        {
            this._atributos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atributos_ = node;
    }

    public PMetodos getMetodos()
    {
        return this._metodos_;
    }

    public void setMetodos(PMetodos node)
    {
        if(this._metodos_ != null)
        {
            this._metodos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metodos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idMolde_)
            + toString(this._atributos_)
            + toString(this._metodos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idMolde_ == child)
        {
            this._idMolde_ = null;
            return;
        }

        if(this._atributos_ == child)
        {
            this._atributos_ = null;
            return;
        }

        if(this._metodos_ == child)
        {
            this._metodos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idMolde_ == oldChild)
        {
            setIdMolde((TIdMolde) newChild);
            return;
        }

        if(this._atributos_ == oldChild)
        {
            setAtributos((PAtributos) newChild);
            return;
        }

        if(this._metodos_ == oldChild)
        {
            setMetodos((PMetodos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
