/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import java.util.*;
import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AFamiliaFamilia extends PFamilia
{
    private PRelacao _relacao_;
    private final LinkedList<PFamiliaFecho> _familiaFecho_ = new LinkedList<PFamiliaFecho>();

    public AFamiliaFamilia()
    {
        // Constructor
    }

    public AFamiliaFamilia(
        @SuppressWarnings("hiding") PRelacao _relacao_,
        @SuppressWarnings("hiding") List<?> _familiaFecho_)
    {
        // Constructor
        setRelacao(_relacao_);

        setFamiliaFecho(_familiaFecho_);

    }

    @Override
    public Object clone()
    {
        return new AFamiliaFamilia(
            cloneNode(this._relacao_),
            cloneList(this._familiaFecho_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFamiliaFamilia(this);
    }

    public PRelacao getRelacao()
    {
        return this._relacao_;
    }

    public void setRelacao(PRelacao node)
    {
        if(this._relacao_ != null)
        {
            this._relacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacao_ = node;
    }

    public LinkedList<PFamiliaFecho> getFamiliaFecho()
    {
        return this._familiaFecho_;
    }

    public void setFamiliaFecho(List<?> list)
    {
        for(PFamiliaFecho e : this._familiaFecho_)
        {
            e.parent(null);
        }
        this._familiaFecho_.clear();

        for(Object obj_e : list)
        {
            PFamiliaFecho e = (PFamiliaFecho) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._familiaFecho_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relacao_)
            + toString(this._familiaFecho_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relacao_ == child)
        {
            this._relacao_ = null;
            return;
        }

        if(this._familiaFecho_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relacao_ == oldChild)
        {
            setRelacao((PRelacao) newChild);
            return;
        }

        for(ListIterator<PFamiliaFecho> i = this._familiaFecho_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFamiliaFecho) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
