/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AIdFecho extends PIdFecho
{
    private TPontoFinal _pontoFinal_;
    private TId _id_;

    public AIdFecho()
    {
        // Constructor
    }

    public AIdFecho(
        @SuppressWarnings("hiding") TPontoFinal _pontoFinal_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setPontoFinal(_pontoFinal_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AIdFecho(
            cloneNode(this._pontoFinal_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdFecho(this);
    }

    public TPontoFinal getPontoFinal()
    {
        return this._pontoFinal_;
    }

    public void setPontoFinal(TPontoFinal node)
    {
        if(this._pontoFinal_ != null)
        {
            this._pontoFinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoFinal_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pontoFinal_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pontoFinal_ == child)
        {
            this._pontoFinal_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pontoFinal_ == oldChild)
        {
            setPontoFinal((TPontoFinal) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
