/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import java.util.*;
import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AInitObjeto extends PInitObjeto
{
    private TId _id_;
    private final LinkedList<PIdFecho> _idFecho_ = new LinkedList<PIdFecho>();
    private PExp _exp_;

    public AInitObjeto()
    {
        // Constructor
    }

    public AInitObjeto(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<?> _idFecho_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setId(_id_);

        setIdFecho(_idFecho_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AInitObjeto(
            cloneNode(this._id_),
            cloneList(this._idFecho_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInitObjeto(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PIdFecho> getIdFecho()
    {
        return this._idFecho_;
    }

    public void setIdFecho(List<?> list)
    {
        for(PIdFecho e : this._idFecho_)
        {
            e.parent(null);
        }
        this._idFecho_.clear();

        for(Object obj_e : list)
        {
            PIdFecho e = (PIdFecho) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._idFecho_.add(e);
        }
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._idFecho_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._idFecho_.remove(child))
        {
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PIdFecho> i = this._idFecho_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PIdFecho) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
