/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AInstanciaExp extends PExp
{
    private TIdMolde _idMolde_;
    private PListaInit _listaInit_;

    public AInstanciaExp()
    {
        // Constructor
    }

    public AInstanciaExp(
        @SuppressWarnings("hiding") TIdMolde _idMolde_,
        @SuppressWarnings("hiding") PListaInit _listaInit_)
    {
        // Constructor
        setIdMolde(_idMolde_);

        setListaInit(_listaInit_);

    }

    @Override
    public Object clone()
    {
        return new AInstanciaExp(
            cloneNode(this._idMolde_),
            cloneNode(this._listaInit_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstanciaExp(this);
    }

    public TIdMolde getIdMolde()
    {
        return this._idMolde_;
    }

    public void setIdMolde(TIdMolde node)
    {
        if(this._idMolde_ != null)
        {
            this._idMolde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idMolde_ = node;
    }

    public PListaInit getListaInit()
    {
        return this._listaInit_;
    }

    public void setListaInit(PListaInit node)
    {
        if(this._listaInit_ != null)
        {
            this._listaInit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaInit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idMolde_)
            + toString(this._listaInit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idMolde_ == child)
        {
            this._idMolde_ = null;
            return;
        }

        if(this._listaInit_ == child)
        {
            this._listaInit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idMolde_ == oldChild)
        {
            setIdMolde((TIdMolde) newChild);
            return;
        }

        if(this._listaInit_ == oldChild)
        {
            setListaInit((PListaInit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
