/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ALInitFecho extends PLInitFecho
{
    private TSeparador _separador_;
    private PInitObjeto _initObjeto_;

    public ALInitFecho()
    {
        // Constructor
    }

    public ALInitFecho(
        @SuppressWarnings("hiding") TSeparador _separador_,
        @SuppressWarnings("hiding") PInitObjeto _initObjeto_)
    {
        // Constructor
        setSeparador(_separador_);

        setInitObjeto(_initObjeto_);

    }

    @Override
    public Object clone()
    {
        return new ALInitFecho(
            cloneNode(this._separador_),
            cloneNode(this._initObjeto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALInitFecho(this);
    }

    public TSeparador getSeparador()
    {
        return this._separador_;
    }

    public void setSeparador(TSeparador node)
    {
        if(this._separador_ != null)
        {
            this._separador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separador_ = node;
    }

    public PInitObjeto getInitObjeto()
    {
        return this._initObjeto_;
    }

    public void setInitObjeto(PInitObjeto node)
    {
        if(this._initObjeto_ != null)
        {
            this._initObjeto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._initObjeto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._separador_)
            + toString(this._initObjeto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._separador_ == child)
        {
            this._separador_ = null;
            return;
        }

        if(this._initObjeto_ == child)
        {
            this._initObjeto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._separador_ == oldChild)
        {
            setSeparador((TSeparador) newChild);
            return;
        }

        if(this._initObjeto_ == oldChild)
        {
            setInitObjeto((PInitObjeto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
