/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AObjetoBlocoFecho extends PBlocoFecho
{
    private PTipoMolde _tipoMolde_;
    private TId _id_;

    public AObjetoBlocoFecho()
    {
        // Constructor
    }

    public AObjetoBlocoFecho(
        @SuppressWarnings("hiding") PTipoMolde _tipoMolde_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setTipoMolde(_tipoMolde_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AObjetoBlocoFecho(
            cloneNode(this._tipoMolde_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAObjetoBlocoFecho(this);
    }

    public PTipoMolde getTipoMolde()
    {
        return this._tipoMolde_;
    }

    public void setTipoMolde(PTipoMolde node)
    {
        if(this._tipoMolde_ != null)
        {
            this._tipoMolde_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoMolde_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoMolde_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoMolde_ == child)
        {
            this._tipoMolde_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoMolde_ == oldChild)
        {
            setTipoMolde((PTipoMolde) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
