/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import java.util.*;
import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosAssinatura extends PParametrosAssinatura
{
    private PParametroAssinatura _parametroAssinatura_;
    private final LinkedList<PParametrosAssinaturaFecho> _parametrosAssinaturaFecho_ = new LinkedList<PParametrosAssinaturaFecho>();

    public AParametrosAssinatura()
    {
        // Constructor
    }

    public AParametrosAssinatura(
        @SuppressWarnings("hiding") PParametroAssinatura _parametroAssinatura_,
        @SuppressWarnings("hiding") List<?> _parametrosAssinaturaFecho_)
    {
        // Constructor
        setParametroAssinatura(_parametroAssinatura_);

        setParametrosAssinaturaFecho(_parametrosAssinaturaFecho_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosAssinatura(
            cloneNode(this._parametroAssinatura_),
            cloneList(this._parametrosAssinaturaFecho_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosAssinatura(this);
    }

    public PParametroAssinatura getParametroAssinatura()
    {
        return this._parametroAssinatura_;
    }

    public void setParametroAssinatura(PParametroAssinatura node)
    {
        if(this._parametroAssinatura_ != null)
        {
            this._parametroAssinatura_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametroAssinatura_ = node;
    }

    public LinkedList<PParametrosAssinaturaFecho> getParametrosAssinaturaFecho()
    {
        return this._parametrosAssinaturaFecho_;
    }

    public void setParametrosAssinaturaFecho(List<?> list)
    {
        for(PParametrosAssinaturaFecho e : this._parametrosAssinaturaFecho_)
        {
            e.parent(null);
        }
        this._parametrosAssinaturaFecho_.clear();

        for(Object obj_e : list)
        {
            PParametrosAssinaturaFecho e = (PParametrosAssinaturaFecho) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._parametrosAssinaturaFecho_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametroAssinatura_)
            + toString(this._parametrosAssinaturaFecho_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametroAssinatura_ == child)
        {
            this._parametroAssinatura_ = null;
            return;
        }

        if(this._parametrosAssinaturaFecho_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametroAssinatura_ == oldChild)
        {
            setParametroAssinatura((PParametroAssinatura) newChild);
            return;
        }

        for(ListIterator<PParametrosAssinaturaFecho> i = this._parametrosAssinaturaFecho_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParametrosAssinaturaFecho) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
