/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosAssinaturaFecho extends PParametrosAssinaturaFecho
{
    private TSeparador _separador_;
    private PParametroAssinatura _parametroAssinatura_;

    public AParametrosAssinaturaFecho()
    {
        // Constructor
    }

    public AParametrosAssinaturaFecho(
        @SuppressWarnings("hiding") TSeparador _separador_,
        @SuppressWarnings("hiding") PParametroAssinatura _parametroAssinatura_)
    {
        // Constructor
        setSeparador(_separador_);

        setParametroAssinatura(_parametroAssinatura_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosAssinaturaFecho(
            cloneNode(this._separador_),
            cloneNode(this._parametroAssinatura_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosAssinaturaFecho(this);
    }

    public TSeparador getSeparador()
    {
        return this._separador_;
    }

    public void setSeparador(TSeparador node)
    {
        if(this._separador_ != null)
        {
            this._separador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separador_ = node;
    }

    public PParametroAssinatura getParametroAssinatura()
    {
        return this._parametroAssinatura_;
    }

    public void setParametroAssinatura(PParametroAssinatura node)
    {
        if(this._parametroAssinatura_ != null)
        {
            this._parametroAssinatura_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametroAssinatura_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._separador_)
            + toString(this._parametroAssinatura_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._separador_ == child)
        {
            this._separador_ = null;
            return;
        }

        if(this._parametroAssinatura_ == child)
        {
            this._parametroAssinatura_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._separador_ == oldChild)
        {
            setSeparador((TSeparador) newChild);
            return;
        }

        if(this._parametroAssinatura_ == oldChild)
        {
            setParametroAssinatura((PParametroAssinatura) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
