/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class ATipoPrimitivo extends PTipoPrimitivo
{
    private TPrimitivo _primitivo_;

    public ATipoPrimitivo()
    {
        // Constructor
    }

    public ATipoPrimitivo(
        @SuppressWarnings("hiding") TPrimitivo _primitivo_)
    {
        // Constructor
        setPrimitivo(_primitivo_);

    }

    @Override
    public Object clone()
    {
        return new ATipoPrimitivo(
            cloneNode(this._primitivo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoPrimitivo(this);
    }

    public TPrimitivo getPrimitivo()
    {
        return this._primitivo_;
    }

    public void setPrimitivo(TPrimitivo node)
    {
        if(this._primitivo_ != null)
        {
            this._primitivo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primitivo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._primitivo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._primitivo_ == child)
        {
            this._primitivo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._primitivo_ == oldChild)
        {
            setPrimitivo((TPrimitivo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
