/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class AVazioListaInit extends PListaInit
{

    public AVazioListaInit()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVazioListaInit();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioListaInit(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
