/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class TContem extends Token
{
    public TContem()
    {
        super.setText("contem");
    }

    public TContem(int line, int pos)
    {
        super.setText("contem");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TContem(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTContem(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TContem text.");
    }
}
