/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class TMolde extends Token
{
    public TMolde()
    {
        super.setText("molde");
    }

    public TMolde(int line, int pos)
    {
        super.setText("molde");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMolde(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMolde(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMolde text.");
    }
}
