/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class TPassa extends Token
{
    public TPassa()
    {
        super.setText("passa");
    }

    public TPassa(int line, int pos)
    {
        super.setText("passa");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPassa(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPassa(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPassa text.");
    }
}
