/* This file was generated by SableCC (http://www.sablecc.org/). */

package bemtevi.node;

import bemtevi.analysis.*;

@SuppressWarnings("nls")
public final class TPor extends Token
{
    public TPor()
    {
        super.setText("por");
    }

    public TPor(int line, int pos)
    {
        super.setText("por");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPor text.");
    }
}
